### ISSUE TITLE
Module non trouvé lors du setup: vine.five

### ISSUE THREAD

**Issue by mdamien** [opendatateam/docker-udata#208]
Voici le log complet de `docker-compose up`: https://gist.github.com/mdamien/0a4a924420616015ee0ec7a9ee1013e8

La partie importante je pense est que `vine.five` n'est pas trouvé

**Comment by abulte** [comment]
Bien vu, on avait raté pas mal de mises à jour 🙈 C'est peut-être mieux depuis les derniers merges ?

**Comment by mdamien** [comment]
Ca a bien résolu le souci :+1: Maintenant j'en ai un autre mais ce sera pour une nouvelle issue :smile:
