### ISSUE TITLE
Segmentation fault de uWSGI

### ISSUE THREAD

**Issue by mdamien** [opendatateam/docker-udata#209]
Le log en question: https://gist.github.com/mdamien/d1a0a67a58b9738b80e0c75a6ba84a62

`uWSGI process XXX got Segmentation Fault` m'a l'air d'être le problème, 

J'essaye de réglé le problème avec la PR #201

EDIT: Je confirme, réglé avec la PR 201

**Comment by abulte** [comment]
Merci, #201 mergé du coup
